# NumPy

## Understanding Data Types in Python


```C
/* C code */
int result = 0;
for(int i=0; i<100; i++){
    result += i;
}
```

While in Python the equivalent operation could be written this way:
```python
# Python code
result = 0
for i in range(100):
    result += i
```


In [1]:
x = 4 

In [2]:
x = 'four'

```C
/* C code */
int x = 4;
x = "four";  // FAILS
```

### A Python Integer Is More Than Just an Integer

```C
struct _longobject {
    long ob_refcnt;
    PyTypeObject *ob_type;
    size_t ob_size;
    long ob_digit[1];
};
```

A single integer in Python 3.4 actually contains four pieces:
- ob_refcnt, a reference count that helps Python silently handle memory allocation and deallocation
- ob_type, which encodes the type of the variable
- ob_size, which specifies the size of the following data members
- ob_digit, which contains the actual integer value that we expect the Python variable to represent.

<img src="https://jakevdp.github.io/PythonDataScienceHandbook/figures/cint_vs_pyint.png" alt="Integer Memory Layout">

### A Python List Is More Than Just a List


In [6]:
l = list(range(10))
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [7]:
type(l)

list

In [8]:
l2 = [str(c) for c in l]
l2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

List ima lahko elemente, ki so raazličnih tipov:
Za vsak element se shrani en kup dodatnih informacij zraven:

In [9]:
l3 = [1, "kk", True]
l3

[1, 'kk', True]

Numpy naredi en objekt, ki samo enkrat shrani podatke, ne za vsak element posebej, zato je bolj učinkovit in hitrejši. 
Slabost tega je, da v numpy lahko shranjujemo samo eleemente istega tipa, ne morejo biti v listu elementi različnega tipa.


<img src="https://jakevdp.github.io/PythonDataScienceHandbook/figures/array_vs_list.png" alt="Array Memory Layout">

### Fixed-Type Arrays in Python


# vektorizacija

Kako pohitrimo kodo. pri pythonu nimamo vpogleda v memory, lahko pa hitreje pišemo program. Pri C ju je ravno obratno, več časa porabiš za pisanje, imaš pa dober vpogled v program. Numpy nam nudi hitro pisanje (ker smo v pythonu) in vpogled v memory. To je vektorizacija.

## How Vectorization Makes Code Faster



<p><img alt="Translating Python code to bytecode" src="https://s3.amazonaws.com/dq-content/289/bytecode.svg"></p>


<table>
<thead>
<tr>
<th>Language Type</th>
<th>Example</th>
<th>Time taken to write program</th>
<th>Control over program performance</th>
</tr>
</thead>
<tbody>
<tr>
<td>High-Level</td>
<td>Python</td>
<td>Low</td>
<td>Low</td>
</tr>
<tr>
<td>Low-Level</td>
<td>C</td>
<td>High</td>
<td>High</td>
</tr>
</tbody>
</table>



<p><img alt="For loop to sum rows" src="https://s3.amazonaws.com/dq-content/289/for_loop.svg"></p>

PRIMER: Seštevamo elemente v listu listov. Python si za vsako zanko vzame čas, sešteva element po element.

In [13]:
my_numbers = [[6,5],[1,3],[5,6]]
sums = []
for row in my_numbers:
    row_sum= row[0] + row[1]
    sums.append(row_sum)
    
print(sums)

[11, 4, 11]


pri vektorizcaiji pa vse opareacije lahko izvajamo hkrati (ne le eno po eno). SIMD je okrajšava za vektorizacijo
Vektorizacija je že implementirana v numpy knjižnico, zato je numpy veliko hitrejši od same python kode.
NUMPY pomeni numerical pyhoon, uporablja se za numerično računanje v pythonu.
Numpy je osnova za ostale knjižnce (pandas npr. recimo temelji na numpy-u).


<p><img alt="Unvectorized operation" src="https://s3.amazonaws.com/dq-content/289/unvectorized.svg"></p>

<p><img alt="Vectorized operation" src="https://s3.amazonaws.com/dq-content/289/vectorized.svg"></p>



## Numpy

Numpy vseuje orodje za linerno algebro, branje, generiranje random števil,...
generiran je bil za obdelovanje velikega števila podatkov. operacije so več desetkrat hitrejše kot v samem pythonu in porabije veliko manj RAMa.
ima zelo dobro dokumentacijo.

In [16]:
#najprej moramo uvoziti numpy knjižnico, da jo lahko uporabljamo
import numpy as np

ndarray: večdimenzionalni array


### NumPy ndarrays



<p><img alt="Dimensional Arrays" src="https://s3.amazonaws.com/dq-content/289/dimensional_arrays.svg"></p>



#### Create an array



In [19]:
#naredimo array
list1 = [6,7.4,8,56,77]

#spremenimo v numpy array
arr1 = np.array(list1)
print(arr1)

[ 6.   7.4  8.  56.  77. ]


vsi elementi ndarraya morajo bii enakega tipa. Če imamo npr. integer in en decimal, bo vse spremenil v decimal.

In [21]:
type(list1)

list

In [22]:
type(arr1)

numpy.ndarray

In [23]:
#večdimenzionalni ndarray
data2 = [[2,4,5.6],[3,7,9]]
arr2 = np.array(data2)
print(arr2)

[[2.  4.  5.6]
 [3.  7.  9. ]]


imamo veliko načinov za definiranje novih ndarrayev:

In [25]:
#ones - naredi matriko enic velikosti (n,m)
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [27]:
#Arange: podobna je funkciji arrange v pythonu
np.arange(0,20,4)

array([ 0,  4,  8, 12, 16])

In [30]:
# zeros
#enodimenzionalni array:
np.zeros((10)) 
#dvodimenzionalni ndarray
np.zeros((3,5) )

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [34]:
#linspace : definiramo interval in povemo na koliko delov želimo, da ga razdeli
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [40]:
#random: števla od 1 do 10, velikost matrike je 4x4
np.random.randint(0,10,(4,4))

array([[5, 3, 7, 2],
       [9, 4, 2, 5],
       [4, 4, 6, 0],
       [9, 8, 0, 4]])

In [43]:
#random.random: random števila med 0 in 1, velikosti 3 x3
np.random.random((3,3))

array([[0.94205927, 0.04114966, 0.29969938],
       [0.76715343, 0.70233411, 0.68278897],
       [0.47694932, 0.87846478, 0.55794307]])

In [44]:
#eye: po diagonali da enice
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [45]:
#full: zgenerira velikost matrike s konstantno vrednostjo
np.full((2,5),7)

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [49]:
#empty: če ima kje shranjeno matriko te velikosti, vrne vrednosti, 
#ki so trenutno v tej matriki, če nima, vrne enice po diagonali
np.empty((4,4))

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [50]:
np.empty((3,3))

array([[0.94205927, 0.04114966, 0.29969938],
       [0.76715343, 0.70233411, 0.68278897],
       [0.47694932, 0.87846478, 0.55794307]])

#### Understanding NumPy ndarrays

In [56]:
data3 = np.random.randint(0,10,(4,7))
print(data3)

[[1 9 9 9 4 1 0]
 [7 2 5 9 4 2 0]
 [7 5 4 0 7 8 9]
 [8 7 9 2 6 4 0]]


In [53]:
#ndim: število dimenzij nd arraya
data3.ndim

2

In [54]:
#shape: pove veikost in dimenzijo (= toliko kot je števil v tuple-u)
data3.shape

(4, 7)

In [59]:
#size: število vseh elementov v arrayu
data3.size

28

In [63]:
#itemsize: pove koliko prostora zavazem ene elemnt v pomnilniku
data3.itemsize

8

In [62]:
#število bytov, ki jih zavzame array
data3.nbytes

224

#### Selecting and Slicing Rows and Items from ndarrays

<p><img alt="Selecting rows from a 2D ndarray" src="https://s3.amazonaws.com/dq-content/289/selection_rows.svg"></p>



This is how we select a single item from a 2D ndarray:

<p><img alt="Selecting a single item from a 2D ndarray" src="https://s3.amazonaws.com/dq-content/289/selection_item.svg"></p>


In [ ]:
# ndarray[n, m]: izberemo elemnt v n-ti vrstici in m-tem stolpcu

Načini izbiranja elementov:
- int 5
- slice 0:5, 5:
- :
- [1,5,8]
- boolean array

In [66]:
test_array = np.random.randint(10, size = (5,5))
test_array

array([[8, 9, 7, 2, 6],
       [5, 9, 0, 7, 5],
       [3, 8, 0, 6, 1],
       [7, 9, 6, 0, 4],
       [0, 3, 3, 5, 2]])

In [77]:
#izberemo prvo vrstico
first_row = test_array[0]
first_row

array([8, 9, 7, 2, 6])

In [78]:
#izberemo zadnjo vrstico
last_row = test_array[-1]
last_row

array([0, 3, 3, 5, 2])

In [82]:
# 2. in 3. vrstica
test_array[[1,2]]
test_array[1:2]

array([[5, 9, 0, 7, 5]])

In [83]:
#vrstica 2 do konca
test_array[1:]

array([[5, 9, 0, 7, 5],
       [3, 8, 0, 6, 1],
       [7, 9, 6, 0, 4],
       [0, 3, 3, 5, 2]])

#### Selecting Columns and Custom Slicing ndarrays

Let's continue by learning how to select one or more columns of data:

<p><img alt="Selecting columns from a 2D ndarray" src="https://s3.amazonaws.com/dq-content/289/selection_columns.svg"></p>



If we wanted to select a partial 1D slice of a row or column, we can combine a single value for one dimension with a slice for the other dimension:

<p><img alt="Selecting partial 1D slices from a 2D ndarray" src="https://s3.amazonaws.com/dq-content/289/selection_1darray.svg"></p>

Lastly, if we wanted to select a 2D slice, we can use slices for both dimensions:

<p><img alt="Selecting a 2D slice from a 2D ndarray" src="https://s3.amazonaws.com/dq-content/289/selection_2darray.svg"></p>



In [84]:
test_array2 = np.random.randint(10, size = (5,5))
test_array2

array([[1, 2, 4, 7, 7],
       [2, 7, 4, 5, 3],
       [6, 8, 6, 5, 3],
       [5, 4, 4, 7, 9],
       [0, 0, 6, 8, 7]])

In [85]:
#stolpec 2
test_array2[:,1]

array([2, 7, 8, 4, 0])

In [87]:
# prvi in drugi stolpec
test_array2[:, 0:2]
test_array2[:, :2]

array([[1, 2],
       [2, 7],
       [6, 8],
       [5, 4],
       [0, 0]])

In [89]:
# stolpec 2,4,5
test_array2[:, [1,3,4]]

array([[2, 7, 7],
       [7, 5, 3],
       [8, 5, 3],
       [4, 7, 9],
       [0, 8, 7]])

In [94]:
#vrstica 3, stolpec elementi 2 do 4
test_array2[2, 1:3]

array([8, 6])

In [ ]:
#elemente v vrstici od 1???
test_array2[]

#### Modify values in ndarray



In [95]:
test_array2

array([[1, 2, 4, 7, 7],
       [2, 7, 4, 5, 3],
       [6, 8, 6, 5, 3],
       [5, 4, 4, 7, 9],
       [0, 0, 6, 8, 7]])

In [97]:
# spremenimo element na mestu (1,1)
test_array2[1,1] = 125
test_array2

array([[  1,   2,   4,   7,   7],
       [  2, 125,   4,   5,   3],
       [  6,   8,   6,   5,   3],
       [  5,   4,   4,   7,   9],
       [  0,   0,   6,   8,   7]])

In [102]:
#PAZI: ker imamo array integerjev, mu bo, če mu spremenimo en element v decimal, odrezal decimalna mesta
#numpy array ima samo en fiksni tip, ki ga določimo ob generiranju arraya
test_array2[0,1] = 16.544
test_array2

array([[  1,  16,   4,   7,   7],
       [  2, 125,   4,   5,   3],
       [  6,   8,   6,   5,   3],
       [  5,   4,   4,   7,   9],
       [  0,   0,   6,   8,   7]])

#### Datatypes

[Več o datatypes](https://docs.scipy.org/doc/numpy/reference/arrays.dtypes.html)

[List of scalars](https://docs.scipy.org/doc/numpy/reference/arrays.scalars.html#arrays-scalars-built-in)

In [101]:
#preberi si o datatipih numpy

In [103]:
x = np.array([1,2])
print(x.dtype) #dtype nam pove, kateri numpy type je uporabljen

int64


In [104]:
x = np.array([1.0,2.6])
print(x.dtype)

float64


In [105]:
np.zeros(10) #ndefault aredi float

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [108]:
#definiramo podatkovni tip elementov v arrayu
np.zeros(10, dtype = np.int16)
np.zeros(10, dtype= 'int16')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

<div class="text_cell_render border-box-sizing rendered_html">
<table>
<thead><tr>
<th>Data type</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr>
<td><code>bool_</code></td>
<td>Boolean (True or False) stored as a byte</td>
</tr>
<tr>
<td><code>int_</code></td>
<td>Default integer type (same as C <code>long</code>; normally either <code>int64</code> or <code>int32</code>)</td>
</tr>
<tr>
<td><code>intc</code></td>
<td>Identical to C <code>int</code> (normally <code>int32</code> or <code>int64</code>)</td>
</tr>
<tr>
<td><code>intp</code></td>
<td>Integer used for indexing (same as C <code>ssize_t</code>; normally either <code>int32</code> or <code>int64</code>)</td>
</tr>
<tr>
<td><code>int8</code></td>
<td>Byte (-128 to 127)</td>
</tr>
<tr>
<td><code>int16</code></td>
<td>Integer (-32768 to 32767)</td>
</tr>
<tr>
<td><code>int32</code></td>
<td>Integer (-2147483648 to 2147483647)</td>
</tr>
<tr>
<td><code>int64</code></td>
<td>Integer (-9223372036854775808 to 9223372036854775807)</td>
</tr>
<tr>
<td><code>uint8</code></td>
<td>Unsigned integer (0 to 255)</td>
</tr>
<tr>
<td><code>uint16</code></td>
<td>Unsigned integer (0 to 65535)</td>
</tr>
<tr>
<td><code>uint32</code></td>
<td>Unsigned integer (0 to 4294967295)</td>
</tr>
<tr>
<td><code>uint64</code></td>
<td>Unsigned integer (0 to 18446744073709551615)</td>
</tr>
<tr>
<td><code>float_</code></td>
<td>Shorthand for <code>float64</code>.</td>
</tr>
<tr>
<td><code>float16</code></td>
<td>Half precision float: sign bit, 5 bits exponent, 10 bits mantissa</td>
</tr>
<tr>
<td><code>float32</code></td>
<td>Single precision float: sign bit, 8 bits exponent, 23 bits mantissa</td>
</tr>
<tr>
<td><code>float64</code></td>
<td>Double precision float: sign bit, 11 bits exponent, 52 bits mantissa</td>
</tr>
<tr>
<td><code>complex_</code></td>
<td>Shorthand for <code>complex128</code>.</td>
</tr>
<tr>
<td><code>complex64</code></td>
<td>Complex number, represented by two 32-bit floats</td>
</tr>
<tr>
<td><code>complex128</code></td>
<td>Complex number, represented by two 64-bit floats</td>
</tr>
</tbody>
</table>

</div>

### Computation on NumPy Arrays: Universal Functions


#### The Slowness of Loops



#### Introducing UFuncs (Universal functions)

[Docs](https://docs.scipy.org/doc/numpy/reference/ufuncs.html())



### Uvoz realnih podatkov


- Row 1 is RatecodeID
- Row 2 is PULocationID
- Row 3 is DOLocationID
- Row 4 is passenger_count
- Row 5 is trip_distance
- Row 6 is fare_amount
- Row 7 is extra
- Row 8 is mta_tax
- Row 9 is tip_amount
- Row 10 is tolls_amount
- Row 11 is improvement_surcharge
- Row 12 is total_amount
- Row 13 is payment_type
- Row 14 is trip_type

### Vector Math




Here's what happened behind the scenes:

<p><img alt="Vectorized Addition" src="https://s3.amazonaws.com/dq-content/289/vectorized_addition.svg"></p>


- `vector_a + vector_b` - Addition
- `vector_a - vector_b7` - Subtraction
- `vector_a * vector_b` - Multiplication (this is unrelated to the vector multiplication used in linear algebra).
- `vector_a / vector_b` - Division
- `vector_a % vector_b` - Modulus (find the remainder when vector_a is divided by vector_b)
- `vector_a ** vector_b` - Exponent (raise vector_a to the power of vector_b)
- `vector_a // vector_b` - Floor Division (divide vector_a by vector_b, rounding down to the nearest integer)


<div class="inner_cell">
<div class="text_cell_render border-box-sizing rendered_html">
<p>The following table lists the arithmetic operators implemented in NumPy:</p>
<table>
<thead><tr>
<th>Operator</th>
<th>Equivalent ufunc</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr>
<td><code>+</code></td>
<td><code>np.add</code></td>
<td>Addition (e.g., <code>1 + 1 = 2</code>)</td>
</tr>
<tr>
<td><code>-</code></td>
<td><code>np.subtract</code></td>
<td>Subtraction (e.g., <code>3 - 2 = 1</code>)</td>
</tr>
<tr>
<td><code>-</code></td>
<td><code>np.negative</code></td>
<td>Unary negation (e.g., <code>-2</code>)</td>
</tr>
<tr>
<td><code>*</code></td>
<td><code>np.multiply</code></td>
<td>Multiplication (e.g., <code>2 * 3 = 6</code>)</td>
</tr>
<tr>
<td><code>/</code></td>
<td><code>np.divide</code></td>
<td>Division (e.g., <code>3 / 2 = 1.5</code>)</td>
</tr>
<tr>
<td><code>//</code></td>
<td><code>np.floor_divide</code></td>
<td>Floor division (e.g., <code>3 // 2 = 1</code>)</td>
</tr>
<tr>
<td><code>**</code></td>
<td><code>np.power</code></td>
<td>Exponentiation (e.g., <code>2 ** 3 = 8</code>)</td>
</tr>
<tr>
<td><code>%</code></td>
<td><code>np.mod</code></td>
<td>Modulus/remainder (e.g., <code>9 % 4 = 1</code>)</td>
</tr>
</tbody>
</table>
<p>Additionally there are Boolean/bitwise operators; we will explore these in <a href="02.06-boolean-arrays-and-masks.html">Comparisons, Masks, and Boolean Logic</a>.</p>

</div>
</div>

[Mathematical expressions](https://docs.scipy.org/doc/numpy-1.14.0/reference/routines.math.html#arithmetic-operations)

### Calculating Statistics For 1D ndarrays



### Calculating Statistics For 2D ndarrays

For now, we're going to look at how we can calculate statistics for two-dimensional ndarrays. If we use the arrays without additional parameters, they will return a single value, just like they do with a 1D array:

<p><img alt="Array method without axis parameter" src="https://s3.amazonaws.com/dq-content/289/array_method_axis_none.svg"></p>

But what if we wanted to find the maximum value of each row? For that, we need to use the axis parameter, and specify a value of 1, which indicates we want to calculate values for each row.

<p><img alt="Array method without axis 1" src="https://s3.amazonaws.com/dq-content/289/array_method_axis_1.svg"></p>

If we want to find the maximum value of each column, we use an axis value of 0:

<p><img alt="Array method without axis 1" src="https://s3.amazonaws.com/dq-content/289/array_method_axis_0.svg"></p>

To help you remember which is which, you can think of the first axis as rows, and the second axis as columns, just in the same way as when we're indexing a 2D NumPy array we use ndarray[row,column]. Then you think about which axis you want to apply the method along. The tricky part is to remember that when you apply the method along one axis, you get results in the other axis. Here is an illustration of that:

<p><img alt="The axis parameter" src="https://s3.amazonaws.com/dq-content/289/axis_param.svg"></p>



### Adding Rows and Columns to ndarrays


### Sorting ndarrays


###  Reading CSV files with NumPy

###  Boolean Arrays





A similar pattern occurs– the 'less than five' operation is applied to each value in the array. The diagram below shows this step by step:

<p><img alt="Vectorized boolean operation" src="https://s3.amazonaws.com/dq-content/290/vectorized_bool.svg"></p>

### Boolean Indexing with 1D ndarrays




<p><img alt="Boolean indexing 1D ndarrays 1" src="https://s3.amazonaws.com/dq-content/290/1d_bool_1.svg"></p>



<p><img alt="Boolean indexing 1D ndarrays 2" src="https://s3.amazonaws.com/dq-content/290/1d_bool_2.svg"></p>




### Boolean Indexing with 2D ndarrays


<p><img alt="Boolean indexing 1D ndarrays 2" src="https://s3.amazonaws.com/dq-content/290/bool_dims.svg"></p>


### Assigning Values in ndarrays

### Subarrays as no-copy views



### Copying Data
